services:
  - type: web
    name: api-key-server
    env: python
    plan: free # Gói miễn phí
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: APP_SECRET_KEY
        sync: false # BẮT BUỘC: Bạn vẫn phải tự set key này trong Environment

